include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = susLANPrefs

susLANPrefs_FILES = PRIMPRootListController.m
susLANPrefs_FRAMEWORKS = UIKit
susLANPrefs_PRIVATE_FRAMEWORKS = Preferences
susLANPrefs_INSTALL_PATH = /Library/PreferenceBundles
susLANPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
